title: Mirigi
description: Mirigi revolutionizes condominium living by offering a digital concierge service that enhances resident-building interactions. It provides luxury interfaces for various services like reservations, valet parking, and deliveries, accessible via mobile devices or in-wall touch panels. Mirigi empowers building staff to deliver exceptional service efficiently, streamlining operations and boosting productivity. With integration into building automation, residents enjoy unprecedented control over their living spaces, including security features. Discover the prestigious buildings that have adopted Mirigi for an elevated lifestyle experience.
##
baseurl: ""
url: ""
exclude: ["README.md"]
sass:
  sass_dir: scss/
# Fallback definitions:

lang: en
languages:
  - en
  - es
  - fr


collections:
  features:
    output: true
  customers:
    output: true

collections_dir: "collections"

# By default data is in english:
# ref: https://jekyllrb.com/docs/configuration/front-matter-defaults/
defaults:
  # Features collection:
  - scope:
      path: 'collections/_features/en'
      type: 'features'
    values:
      permalink: 'en/features/:title'
      lang: "en"
  - scope:
      path: 'collections/_features/es'
      type: 'features'
    values:
      permalink: 'es/funcionalidades/:title'
      lang: "es"
  - scope:
      path: 'collections/_features/fr'
      type: 'features'
    values:
      permalink: 'fr/caracteristiques/:title'
      lang: "fr"
  # customers collection:
  - scope:
      path: 'collections/_customers'
      type: 'customers'
    values:
      layout: customer
  - scope:
      path: 'collections/_customers/en'
      type: 'customers'
    values:
      permalink: 'en/customers/:title'
      lang: "en"
  - scope:
      path: 'collections/_customers/es'
      type: 'customers'
    values:
      permalink: 'es/clientes/:title'
      lang: "es"
  - scope:
      path: 'collections/_customers/fr'
      type: 'customers'
    values:
      permalink: 'fr/clients/:name'
      lang: "fr"
  # Translations
  - scope:
      path: "en/"
    values:
      lang: "en"
  - scope:
      path: "es/"
    values:
      lang: "es"
  - scope:
      path: "fr/"
    values:
      lang: "fr"




#jekyll plugins for TOC and sitemap
plugins:
  #- jekyll-toc
  - jekyll-sitemap
